packages/ui/src/exports/nuxt.js
In https://github.com/nuxt/framework/pull/7116 we made a breaking change allowing modules to use RC constraints. This PR fixes this.
**What kind of change does this PR introduce?** (check at least one)
**Does this PR introduce a breaking change?** (check one)
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
**Other information:**
=> fix: update nuxt compatibility constraints

package.json, pnpm-lock.yaml
=> Disable scripts when used as dependency

.changeset/config.json, .scripts/changelog.js, pnpm-lock.yaml
=> chore: add custom changelog

.changeset/pink-bugs-rescue.md, packages/ui/src/components/menu/MenuItem.vue
=> fix(menu-item): link colors

.changeset/silent-insects-learn.md, package.json, packages/docs/package.json, packages/docs/src/layouts/default.vue, packages/nuxt-demo/package.json, packages/ui/.eslintrc.cjs, packages/ui/src/components/helpers/InputError.tsx, packages/ui/src/components/icon/__tests__/Icon.spec.ts, pnpm-lock.yaml
=> chore: update eslint dependencies

.changeset/flat-apples-greet.md, packages/docs/src/pages/component/menu/usage.vue, packages/ui/src/components/menu/MenuItem.vue
=> fix(menu-item): href binding

.changeset/green-dogs-repair.md, packages/ui/docs/components/toolbar/Toolbar.vue, packages/ui/docs/pages/component/form/usage.vue, packages/ui/src/components/checkbox/theme/Checkbox.base.theme.ts, packages/ui/src/components/inputFooter/theme/InputFooter.base.theme.ts, packages/ui/src/components/label/theme/Label.base.theme.ts, packages/ui/src/components/radio/theme/Radio.base.theme.ts, packages/ui/src/components/scroll/Scroll.vue
=> style(base): adjust input footer height

.changeset/dry-spies-unite.md, packages/ui/src/components/accordion/AccordionItem.vue, packages/ui/src/components/accordion/theme/AccordionItem.base.theme.ts, packages/ui/src/components/alert/Alert.vue, packages/ui/src/components/notifications/Notifications.vue, packages/ui/src/components/stepper/Stepper.vue, packages/ui/src/components/tab/Tab.vue, packages/ui/src/components/table/Table.vue
=> fix: default button types

.changeset/heavy-dots-sparkle.md, packages/create-ui/templates/nuxt/base/nuxt.config.ts, packages/create-ui/templates/nuxt/base/package.json, packages/demo-nuxt/nuxt.config.ts, packages/demo-nuxt/package.json, packages/ui/exports/nuxt.plugin.js, packages/ui/package.json, packages/ui/src/components/popover/Popover.vue, packages/ui/src/create.ts, packages/ui/src/themes/base/index.ts, packages/ui/src/themes/base/styles.ts, packages/ui/src/themes/carbon/index.ts, packages/ui/src/themes/carbon/styles.ts, pnpm-lock.yaml
=> fix(nuxt): theme inject key

.changeset/great-schools-attend.md, packages/create-ui/templates/nuxt/base/nuxt.config.ts, packages/create-ui/templates/vue/entry/default/src/main.js, packages/create-ui/templates/vue/entry/pinia/src/main.js, packages/create-ui/templates/vue/entry/router-and-pinia/src/main.js, packages/create-ui/templates/vue/entry/router/src/main.js, packages/demo-nuxt/nuxt.config.ts, packages/ui/docs/pages/index.vue
=> chore: update create to use basetheme

.changeset/tiny-chairs-lie.md, packages/ui/src/components/button/Button.vue
=> fix(button): ts link to as object

.changeset/polite-hounds-fix.md, packages/ui/src/components/carousel/Carousel.vue
=> fix(carousel): bind total and current to slots

.changeset/tough-trees-study.md, packages/ui/docs/pages/component/slider/usage.vue, packages/ui/src/components/slider/Slider.vue, packages/ui/src/components/slider/theme/Slider.base.theme.ts, packages/ui/src/components/slider/theme/Slider.carbon.theme.ts
=> feat(slider): input range refactor

.changeset/late-lizards-promise.md, packages/ui/docs/pages/component/menu/usage.vue, packages/ui/src/components/drawer/Drawer.vue, packages/ui/src/components/drawer/theme/Drawer.base.theme.ts, packages/ui/src/components/menu/Menu.vue, packages/ui/src/components/menu/MenuItem.vue, packages/ui/src/components/menu/theme/MenuItem.base.theme.ts
=> feat(menu): add minimal version

.changeset/blue-roses-tickle.md, packages/ui/src/components/formGroup/FormGroup.vue
=> fix(formgroup): keyup space validate

.changeset/chilly-cups-doubt.md, packages/ui/src/components/datepicker/Datepicker.vue, packages/ui/src/components/datepicker/theme/Datepicker.base.theme.ts, packages/ui/src/components/slider/Slider.vue, packages/ui/src/components/slider/theme/Slider.base.theme.ts
=> fix(datepicker): theme styles

.changeset/tough-terms-allow.md, packages/ui/src/components/form/Form.vue, packages/ui/src/components/modal/Modal.vue, packages/ui/src/components/modal/theme/Modal.base.theme.ts, packages/ui/src/composables/useFocusTrap.ts
=> fix(modal): center align and arrow navigation

.changeset/famous-glasses-dream.md, packages/ui/src/components/menu/MenuItem.vue
=> fix(MenuItem): router link to computed href

.changeset/tricky-elephants-deliver.md, packages/ui/src/components/modal/theme/Modal.base.theme.ts, packages/ui/src/components/modal/theme/Modal.carbon.theme.ts
=> Fix: Modal handing 'full' size option.

.changeset/fast-clouds-listen.md, packages/ui/src/components/select/Select.vue
=> fix(select): clear listeners on unmount

.changeset/pink-rabbits-cheat.md, packages/ui/docs/pages/component/input/usage.vue, packages/ui/src/components/input/Input.vue, packages/ui/src/components/textarea/Textarea.vue
=> chore(input): allow data attrs

.changeset/tall-rings-speak.md, packages/ui/docs/pages/component/select/usage.vue, packages/ui/src/components/select/Select.vue, packages/ui/src/components/select/theme/Select.base.theme.ts, packages/ui/src/components/select/theme/Select.carbon.theme.ts
=> feat(select): add filter action

.changeset/weak-radios-share.md, .github/workflows/pr_check.yml, packages/ui/src/components/datepicker/Datepicker.vue
=> fix(datepicker): template slots

.changeset/clever-falcons-listen.md, .vscode/extensions.json, packages/ui/docs/pages/component/menu/usage.vue, packages/ui/src/components/menu/MenuItem.vue, packages/ui/src/components/menu/theme/MenuItem.base.theme.ts
=> fix(menuitem): link object

.changeset/clean-ads-grow.md, packages/ui/src/components/table/Table.vue
=> fix(Table): key prop id type

.changeset/weak-otters-sort.md, packages/ui/docs/pages/component/select/multiple.vue, packages/ui/src/components/menu/MenuItem.vue, packages/ui/src/components/menu/theme/MenuItem.base.theme.ts, packages/ui/src/components/select/Select.vue
=> feat(select): multi selection with checkboxes

.changeset/tricky-shoes-relax.md, packages/ui/docs/pages/component/select/multiple.vue, packages/ui/docs/pages/component/select/usage.vue, packages/ui/src/components/select/Select.vue, packages/ui/src/components/select/theme/Select.base.theme.ts
=> feat(select): add clearable option, improve truncate

.changeset/grumpy-plants-shout.md, packages/ui/docs/pages/component/datepicker/usage.vue, packages/ui/docs/pages/component/table/usage.vue, packages/ui/src/components/datepicker/Datepicker.vue, packages/ui/src/components/select/Select.vue, packages/ui/src/components/select/theme/Select.base.theme.ts, packages/ui/src/components/table/Table.vue, packages/ui/src/components/table/TableHeader.vue, packages/ui/src/components/table/theme/TableHead.base.theme.ts, packages/ui/src/components/table/theme/TableHeader.base.theme.ts, packages/ui/src/components/table/theme/TableRow.base.theme.ts
=> feat(table): add tooltip for header

.changeset/smart-apricots-visit.md, packages/ui/src/components/select/Select.vue
=> fix(select): hidden tags count
